language: generic
deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  on:
    branch: master
  provider: s3
  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  # Name of the S3 bucket to which your site should be uploaded.
  bucket: dev.loanwat.ch
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  # Set the Cache-Control header.
  cache_control: "max-age=21600"
  acl: public_read
